apiVersion: v1
kind: ConfigMap
metadata:
  name: groupsapp-config
  namespace: groupsapp
data:
  AMQP_URL: "amqp://guest:guest@rabbitmq:5672/"
  CONSUL_URL: "http://consul:8500"
  ACCESS_TOKEN_EXPIRE_MINUTES: "120"
  USERS_GRPC_ADDR: "users-auth-service:50051"
  GROUPS_GRPC_ADDR: "groups-service:50052"
  UPLOAD_DIR: "/data/uploads"
  PUBLIC_URL_BASE: "/uploads"
---
apiVersion: v1
kind: Secret
metadata:
  name: groupsapp-secret
  namespace: groupsapp
type: Opaque
stringData:
  SECRET_KEY: "groupsapp-super-secret-change-me-32chars"
  POSTGRES_PASSWORD: "groupsapp"
